language: ruby
sudo: false
script:
- gem update --system
- gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
- bundle install
- bundle exec middleman build
after_success:
- .travis/publish-site.sh
